package com.handler;

import com.jdbc.bean.WrapStatement;
import io.netty.buffer.ByteBuf;
import io.netty.channel.ChannelHandlerContext;

import java.sql.SQLException;

import static com.handler.IOHandler.*;

public class StatementHandler {

    public static void handler(WrapStatement statement, ByteBuf src, ChannelHandlerContext out)
            throws SQLException {
        String mName = IOHandler.readByteLen(src);
        if ("executeQuery".equals(mName)) {
            String sql = readIntLen(src);
            UserHandler.authSql(statement.getWrapConnect(), statement.getUser(), sql);
            statement.executeQuery(sql, out);
        } else if ("executeUpdate".equals(mName)) {
            short pc = src.readByte();
            String sql = readIntLen(src);
            UserHandler.authSql(statement.getWrapConnect(), statement.getUser(), sql);
            int count;
            if (1 == pc) count = statement.executeUpdate(sql);
            else {
                int arrSize = src.readShort();
                short type = src.readByte();
                if (0 == arrSize) {
                    if (0 != type) throw new SQLException("executeUpdate[autoGeneratedKeys] type[" +
                            type + "] error");
                    count = statement.executeUpdate(sql, src.readInt());
                } else {
                    if (0 == type) {
                        int[] columnIndexes = readInt(arrSize, src);
                        count = statement.executeUpdate(sql, columnIndexes);
                    } else if (1 == type) {
                        String[] columnNames = readShortLen(arrSize, src);
                        count = statement.executeUpdate(sql, columnNames);
                    } else throw new SQLException("executeUpdate[array] type[" + type + "] error");
                }
            }
            out.write(writeInt(OK, count));
        } else if ("execute".equals(mName)) {
            short pc = src.readByte();
            String sql = readIntLen(src);
            UserHandler.authSql(statement.getWrapConnect(), statement.getUser(), sql);
            boolean bool;
            if (1 == pc) bool = statement.execute(sql);
            else {
                int arrSize = src.readShort();
                short type = src.readByte();
                if (0 == arrSize) {
                    if (0 != type) throw new SQLException("execute[autoGeneratedKeys] type[" + type + "] error");
                    bool = statement.execute(sql, src.readInt());
                } else {
                    if (0 == type) {
                        int[] columnIndexes = readInt(arrSize, src);
                        bool = statement.execute(sql, columnIndexes);
                    } else if (1 == type) {
                        String[] columnNames = readShortLen(arrSize, src);
                        bool = statement.execute(sql, columnNames);
                    } else throw new SQLException("executeUpdate[array] type[" + type + "] error");
                }
            }
            out.write(writeShortStr(OK, bool));
        } else if ("getGeneratedKeys".equals(mName)) {
            statement.getGeneratedKeys(out);
        } else if ("executeBatch".equals(mName)) {
            int arrSize = src.readShort();
            short type = src.readByte();
            if (1 != type) throw new SQLException("executeBatch param type[" + type + "] error");
            String[] sqls = readIntLen(arrSize, src);
            for (String sql : sqls) UserHandler.authSql(statement.getWrapConnect(), statement.getUser(), sql);
            int[] code = statement.executeBatch(sqls);
            out.write(writeInt(OK, code));
        } else if ("setFetchDirection".equals(mName)) {
            statement.setFetchDirection(src.readInt());
            out.write(writeByte(OK));
        } else if ("setFetchSize".equals(mName)) {
            statement.setFetchSize(src.readInt());
            out.write(writeByte(OK));
        } else if ("getResultSet".equals(mName)) {
            statement.getResultSet(out);
        } else if ("close".equals(mName)) {
            statement.close();
            out.write(writeByte(OK));
        } else throw new SQLException("statementMethod[" + mName + "] is not support");
    }
}
